spring.application.name=loyalty service
server.port=8084

spring.datasource.url=jdbc:mysql://172.245.112.93:3306/Advocacy_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=qa_user2
spring.datasource.password=IotQA@4646
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
